FROM python:3.8

RUN mkdir -p /data/epb
WORKDIR /data/epb
COPY requirements.txt /data/epb/

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

# Prepare
COPY . /data/epb/

RUN groupadd -g 1019 orfeus && \
    useradd -u 994 -g 1019 orfeus

RUN chown -R orfeus:orfeus /data
USER orfeus