FROM phusion/baseimage:latest

# Initialize
CMD ["/sbin/my_init"]

RUN mkdir -p /data/epb
WORKDIR /data/epb
COPY requirements.txt /data/epb/

# Setup
RUN apt-get update -y
RUN apt-get install -y \
    python3-dev \
    python3-setuptools \
    python3-pip

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install numpy
RUN pip3 install -r requirements.txt

# Prepare
COPY . /data/epb/

RUN groupadd -g 1019 orfeus && \
    useradd -u 994 -g 1019 orfeus

# Clean up (baseimage recommended)
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN chown -R orfeus:orfeus /data
USER orfeus