version: '2'
services:
  epb:
    restart: always
    build: ./eida-portal-backend/
    user: "994:1019"
    ports:
      - "8010:8010"
    volumes:
      - ./eida-portal-backend/app/db:/data/epb/db
    networks:
      - epb_net
    command: gunicorn -b localhost:8010 -w 2 app:app

networks:
  epb_net: